export const LISTAR_JUGADORES = 'LISTAR_JUGADORES';
export const ACTIVAR_PAGADO = 'ACTIVAR_PAGADO';
export const ACTUALIZAR_JUGADOR = 'ACTIVAR_PAGADO';
export const ACTUALIZAR_MONTO = 'ACTUALIZAR_MONTO';
export const ACTUALIZAR_TIPO_JUEGO = 'ACTUALIZAR_TIPO_JUEGO';
export const ACTUALIZAR_NOMBRE_JUGADOR = 'ACTUALIZAR_NOMBRE_JUGADOR';
export const ACTUALIZAR_JUEGO = 'ACTUALIZAR_JUEGO';